version: "2"
services:
  fs-user:
    image: asrsa/fs-sensor

    ports:
      - 8081:8081

    volumes:
      - ./api/target/api-1.0-SNAPSHOT.jar:/api/target/api-1.0-SNAPSHOT.jar

    command:
      java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7999 -cp classes:dependency/* com.kumuluz.ee.EeApplication

